return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "lua",
      "python",
      "bash",
      "css",
      "html",
      "javascript",
      "markdown",
      "csv",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitcommit",
      "gitignore",
      "go",
      "gomod",
      "gosum",
      "gpg",
      "graphql",
      "jq",
      "json",
      "json5",
      "php",
      "sql",
      "ssh_config",
      "terraform",
      "toml",
      "xml",
      "yaml",
    },
  },
}
